name: chrombert_training
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - arrow-cpp=11.0.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - colorama=0.4.6
  - dataclasses=0.8
  - dill
  - frozenlist=1.5.0
  - gflags=2.2.2
  - glog=0.5.0
  - grpc-cpp=1.48.2
  - huggingface_hub=0.29.2
  - icu=73.1
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.12.1
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.57.0
  - libprotobuf=3.20.3
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libuuid=1.41.5
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - numexpr=2.10.1
  - openssl=3.0.16
  - orc=1.7.4
  - packaging=24.2
  - pip
  - pyarrow
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2023.3
  - python-xxhash=3.5.0
  - pyyaml=6.0.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - scikit-learn==1.6.1
  - setuptools=75.8.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tokenizers==0.21.0
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wheel=0.45.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - accelerate==1.5.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - attrs==25.3.0
      - biopython==1.85
      - boto3==1.37.11
      - botocore==1.37.11
      - charset-normalizer==3.4.1
      - click==8.1.8
      - datasets==3.4.1
      - evaluate==0.4.3
      - filelock==3.17.0
      - fsspec==2023.10.0
      - grpcio==1.71.0
      - huggingface-hub==0.30.2
      - idna==3.10
      - jinja2==3.1.6
      - jmespath==1.0.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.2.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - pandas==2.2.2
      - patsy==1.0.1
      - propcache==0.3.0
      - protobuf==6.30.0
      - psutil==7.0.0
      - pyahocorasick==2.1.0
      - pygments==2.19.1
      - pytz==2025.1
      - regex==2024.11.6
      - rich==13.9.4
      - s3transfer==0.11.4
      - sacremoses==0.1.1
      - safetensors==0.5.3
      - scipy==1.10.1
      - sentencepiece==0.2.0
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.6.0
      - torch==2.6.0
      - triton==3.2.0
      - tzdata==2025.1
      - werkzeug==3.1.3
      - yarl==1.18.3
